# Generated by Django 2.2.4 on 2020-12-17 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_favorites', '0003_auto_20201217_0801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='desc',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
